### ISSUE TITLE
Error when running gen_scl_nat_main.py file

### ISSUE THREAD

**Issue by cheemsbaby** [jpeper/GEN_SCL_NAT#3]
restaurant_output
Traceback (most recent call last):
  File "E:\hmz\code\nlp\情感分析\GEN_SCL_NAT-main\source\gen_scl_nat_main.py", line 432, in <module>
    tokenizer = T5Tokenizer.from_pretrained(args.model_name_or_path)
  File "D:\anaconda\envs\GEN_SCL_NAT-main\lib\site-packages\transformers\tokenization_utils_base.py", line 1768, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'models/GEN_SCL_NAT-RESTAURANT'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'models/GEN_SCL_NAT-RESTAURANT' is the correct path to a directory containing all relevant files for a T5Tokenizer tokenizer.

**Comment by VanDijksty** [comment]
hello, I'm also trying to do the same thing as you do. Because the author already trained the model, you should  download the trained model that is available at https://drive.google.com/drive/folders/1g30oS8hpqn6tAGNyLbOwEoLLmhHOy94o  to your local file, which the author mentioned in README.md. I suggest you go take a look at README.md.
